name: CV Deploy

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  deploy_portfolio:
    name: Deploying my portfolio via ci/cd pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: echo for testing
        run: echo "This is working"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.IP_ADDRESS}}
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            export PATH=/home/ubuntu/.nvm/versions/node/v22.14.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
            cd virtual-iot-dashboard
            expect -c 'spawn git pull; expect "Enter passphrase for key"; send "${{secrets.PASSPHRASE}}\r"; expect eof'
            bun install
            bun run build
            pm2 restart 4
            echo "Deployed successfully"
            exit
            echo ls
  